set_property BITSTREAM.GENERAL.COMPRESS True [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports {vga_r[0]}]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports {vga_r[1]}]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS33} [get_ports {vga_r[2]}]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports {vga_r[3]}]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {vga_r[4]}]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports {vga_r[5]}]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports {vga_r[6]}]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {vga_r[7]}]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports {vga_g[0]}]
set_property -dict {PACKAGE_PIN U15 IOSTANDARD LVCMOS33} [get_ports {vga_g[1]}]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports {vga_g[2]}]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports {vga_g[3]}]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports {vga_g[4]}]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports {vga_g[5]}]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVCMOS33} [get_ports {vga_g[6]}]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVCMOS33} [get_ports {vga_g[7]}]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports {vga_b[0]}]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS33} [get_ports {vga_b[1]}]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports {vga_b[2]}]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS33} [get_ports {vga_b[3]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {vga_b[4]}]
set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVCMOS33} [get_ports {vga_b[5]}]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {vga_b[6]}]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVCMOS33} [get_ports {vga_b[7]}]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports vga_h_sync]
set_property -dict {PACKAGE_PIN T12 IOSTANDARD LVCMOS33} [get_ports vga_v_sync]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports vga_de]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports vga_mode]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports vga_ud]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33} [get_ports vga_dclk]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33} [get_ports vga_dithb]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports vga_rst]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33} [get_ports vga_lr]

set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS25} [get_ports btn_lsb]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS25} [get_ports btn_usb]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS25} [get_ports btn_am]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS25} [get_ports btn_fm]
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS25} [get_ports btn_dig]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS25} [get_ports btn_cw]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS25} [get_ports btn_tune]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS25} [get_ports btn_band2]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS25} [get_ports btn_band3]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS25} [get_ports btn_band4]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS25} [get_ports btn_band5]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS25} [get_ports btn_band6]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS25} [get_ports btn_band7]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS25} [get_ports btn_band8]

set_false_path -from [get_clocks clk_fpga_1] -to [get_clocks clk_fpga_1]
